monitoring.api.url=https://monitoring-app.on-forge.com/api/v1
monitoring.api.token=150|MwnRrLsuYTIbPqee4mtOOGw3MsGBnOGSh9it8S6B62671e0b
monitoring.api.application-id=019d2f57-391f-7185-8902-f81bf8326da6