monitoring.api.url=https://monitoring-app.on-forge.com/api/v1
monitoring.api.token=303|OM4EIgAIqSaamIhlz5CuZaVBd5L1fdW5UxLENMqd6bbc1c7f
monitoring.api.application-id=019d2974-9fd9-7238-9e44-bcf7326d7f8e